const sources = [
  "The Indian Express",
  "Moneycontrol",
  "The Verge",
  "Engadget",
  "TechCrunch",
  "Gizmodo",
  "WIRED",
  "9to5Google",
  "XDA Developers",
  "HT Tech",
  "9to5Mac",
  "Forbes",
  "Business Insider",
  "CNET",
  "Mashable",
  "USA TODAY",
  "Digital Trends",
  "Digit",
  "Mac Rumors",
  "PCMag",
  "The Cult of Mac",
  "ZDNet",
  "The Next Web",
  "NPR",
  "Bloomberg",
  "VICE",
  "MIT Technology Review",
  "The Guardian",
  "VentureBeat",
  "Ars Technica",
  "Polygon",
  "IGN",
  "CNBC",
  "Gamesradar",
  "Vox.com",
];

module.exports = sources;
