# This workflow will do a clean install of node dependencies, and run the script across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NEWS webhook

on:
  push:
    branch: main
  schedule:
    - cron: "30 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependancies
        run: npm install
      - name: Run script
        run: node ./src/news.js
        env:
          NEWS_HOOK: ${{ secrets.NEWS_HOOK }}
          NEWS_KEY: ${{ secrets.NEWS_KEY }}
